{% set name = "ipynao" %}
{% set version = "0.7.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipynao-{{ version }}.tar.gz
  sha256: 6c8ec9569a481aea3654d3f7cf16166a56780c365bf15b1338ebe0970d069b61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab ==3.*
    - pip
  run:
    - python >=3.7
    - ipywidgets >=7.0.0

test:
  imports:
    - ipynao
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyter-robotics/ipynao/
  summary: A widget library for controlling Nao
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ihuicatl
