{% set name = "ipynao" %}
{% set version = "0.8.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipynao-{{ version }}.tar.gz
  sha256: d7806df4bd65584b1de116256722baf8e195a824e6046a2c67887b6c6cc3d462

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab ==3.*
    - pip
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.0.0

test:
  imports:
    - ipynao
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyter-robotics/ipynao/
  summary: A widget library for controlling Nao
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - IsabelParedes
